name: BetterFishing
main: de.aestis.betterfishing.Main
description: Inspired by MoreFish
version: 0.9.1
author: Guerkchen385
api-version: 1.13
commands:
   bf:
      description: Main Command for this Plugin